# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-05 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file', models.FileField(default=b'file', upload_to=b'upload')),
            ],
        ),
        migrations.CreateModel(
            name='SignupMailConfirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_code', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default=b'First Name', max_length=12)),
                ('lname', models.CharField(default=b'Last Name', max_length=12)),
                ('profile_image', models.ImageField(default=b'avatar.png', upload_to=b'profile')),
                ('cover', models.ImageField(default=b'cover.png', upload_to=b'cover')),
                ('status', models.TextField(default=b'Your Bio')),
                ('profile_status', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dob', models.CharField(default=b'DD-MM-YYYY', max_length=12)),
                ('about_me', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('verify', models.BooleanField(default=False)),
                ('otp', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Users'),
        ),
        migrations.AddField(
            model_name='signupmailconfirm',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users'),
        ),
    ]
